spring.application.name=notification-service

server.port=9050
server.servlet.context-path=/notifications
#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/connectU-notificationsDB

spring.config.import=configserver:http://localhost:8888